import Header from '@/components/Header'
import './globals.css'
import { Raleway } from 'next/font/google';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const raleway = Raleway({
  subsets: ["latin", "cyrillic"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={raleway.className}>
      <body className=' bg-main-dark text-white ' >
        <div className='
        .container max-w-[1278px] mx-auto relative
        xl:max-w-[1018px]
        lg:max-w-[758px]
        md:max-w-[634px]
        sm:max-w-[468px]
        ' >
          <Header />
          {children}
        </div>
      </body>
    </html>
  )
}
